# Generated by Django 6.0.7 on 2026-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
