# Generated by Django 6.0.7 on 2026-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
