# Generated by Django 6.0.7 on 2026-07-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0005_product_color_product_condition_product_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
